# Generated by Django 4.2.16 on 2024-11-04 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djblog', '0003_alter_post_status'),
        ('djblog', '0004_alter_post_slug'),
    ]

    operations = [
    ]
