# Generated by Django 4.2.16 on 2024-11-05 08:33
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djblog', '0007_post_tags'),
    ]

    operations = [
        TrigramExtension()
    ]
